apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  namespace: dev
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wp-pod
      namespace: dev
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_NAME
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: db_name

        - name: WORDPRESS_DB_USER
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: db_user

        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: db_password

        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-connection-configmap
              key: database_url
