apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp-deploy
  name: nodeapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-deploy
  template:
    metadata:
      labels:
        app: nodeapp-deploy
    spec:
      containers:
      - image: paawanyadav/nodeapp:latest
        name: nodeapp
